/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 29 23:24:12 GMT 2023
 */

package paymentStrategy;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import paymentStrategy.Context;
import paymentStrategy.MobilePaymentProvider;
import paymentStrategy.PaymentInfo;
import paymentStrategy.PaymentProvider;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Context_ESTest extends Context_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MobilePaymentProvider mobilePaymentProvider0 = new MobilePaymentProvider();
      PaymentInfo paymentInfo0 = new PaymentInfo(1, 1, "8u", "8u", 596);
      Context context0 = new Context(mobilePaymentProvider0);
      boolean boolean0 = context0.execute(paymentInfo0, 596);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MobilePaymentProvider mobilePaymentProvider0 = new MobilePaymentProvider();
      Context context0 = new Context(mobilePaymentProvider0);
      PaymentInfo paymentInfo0 = new PaymentInfo(596, 1626, (String) null, "[S3pEb<(/-]^K", 0);
      boolean boolean0 = context0.execute(paymentInfo0, 1626);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Context context0 = new Context((PaymentProvider) null);
      // Undeclared exception!
      try { 
        context0.execute((PaymentInfo) null, 1.0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("paymentStrategy.Context", e);
      }
  }
}
