/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 29 23:33:05 GMT 2023
 */

package users;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import users.NonFacultyStaff;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class NonFacultyStaff_ESTest extends NonFacultyStaff_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NonFacultyStaff nonFacultyStaff0 = new NonFacultyStaff("", "");
      int int0 = nonFacultyStaff0.getParkingRate();
      assertEquals(10, int0);
  }
}
