/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 29 23:22:28 GMT 2023
 */

package parkingState;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import parkingState.Occupied;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Occupied_ESTest extends Occupied_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Occupied occupied0 = new Occupied((String) null);
      String string0 = occupied0.handleState();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Occupied occupied0 = new Occupied("");
      String string0 = occupied0.handleState();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Occupied occupied0 = new Occupied("w@)K441:1}GZE)P&");
      String string0 = occupied0.handleState();
      assertEquals("w@)K441:1}GZE)P&", string0);
  }
}
