/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 29 23:22:39 GMT 2023
 */

package paymentStrategy;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.util.MockDate;
import org.junit.runner.RunWith;
import paymentStrategy.PaymentInfo;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PaymentInfo_ESTest extends PaymentInfo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PaymentInfo paymentInfo0 = new PaymentInfo(0, (-1354), "CXP", "", 0);
      int int0 = paymentInfo0.getSecurityCode();
      assertEquals("CXP", paymentInfo0.getBillingAddress());
      assertEquals(0, paymentInfo0.getCardNum());
      assertEquals("", paymentInfo0.getBillingName());
      assertEquals((-1354), paymentInfo0.getExpDate());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PaymentInfo paymentInfo0 = new PaymentInfo((-2703), 0, "S>5+", "S>5+", (-2703));
      int int0 = paymentInfo0.getSecurityCode();
      assertEquals(0, paymentInfo0.getExpDate());
      assertEquals((-2703), int0);
      assertEquals((-2703), paymentInfo0.getCardNum());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PaymentInfo paymentInfo0 = new PaymentInfo(0, 0, "paymentStrategy.PaymentInfo", "paymentStrategy.PaymentInfo", 0);
      assertEquals(0, paymentInfo0.getExpDate());
      
      paymentInfo0.setExpDate((-1));
      int int0 = paymentInfo0.getExpDate();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PaymentInfo paymentInfo0 = new PaymentInfo(0, 0, (String) null, (String) null, (-1));
      int int0 = paymentInfo0.getCardNum();
      assertEquals((-1), paymentInfo0.getSecurityCode());
      assertEquals(0, paymentInfo0.getExpDate());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PaymentInfo paymentInfo0 = new PaymentInfo(2978, 2978, (String) null, "nv", 2978);
      paymentInfo0.setCardBallance(2978);
      double double0 = paymentInfo0.getCardBallance();
      assertEquals(2978.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PaymentInfo paymentInfo0 = new PaymentInfo(0, 0, "=.L'q<OwE)-,sgXG", "=.L'q<OwE)-,sgXG", 0);
      paymentInfo0.setCardBallance((-1.0));
      double double0 = paymentInfo0.getCardBallance();
      assertEquals((-1.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PaymentInfo paymentInfo0 = new PaymentInfo(1, 1, "", (String) null, 1517);
      String string0 = paymentInfo0.getBillingName();
      assertEquals(1517, paymentInfo0.getSecurityCode());
      assertNull(string0);
      assertEquals(1, paymentInfo0.getCardNum());
      assertEquals(1, paymentInfo0.getExpDate());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PaymentInfo paymentInfo0 = new PaymentInfo(2978, 2978, (String) null, "nv", 2978);
      paymentInfo0.setBillingName("");
      paymentInfo0.getBillingName();
      assertEquals(2978, paymentInfo0.getSecurityCode());
      assertEquals(2978, paymentInfo0.getExpDate());
      assertEquals(2978, paymentInfo0.getCardNum());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PaymentInfo paymentInfo0 = new PaymentInfo(2978, 2978, (String) null, "nv", 2978);
      String string0 = paymentInfo0.getBillingAddress();
      assertEquals(2978, paymentInfo0.getCardNum());
      assertNull(string0);
      assertEquals(2978, paymentInfo0.getExpDate());
      assertEquals(2978, paymentInfo0.getSecurityCode());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PaymentInfo paymentInfo0 = new PaymentInfo(1, 2377, "|t(?w|E.B", "L%P\"uOcS>V", 1);
      assertEquals("|t(?w|E.B", paymentInfo0.getBillingAddress());
      
      paymentInfo0.setBillingAddress("");
      paymentInfo0.getBillingAddress();
      assertEquals(1, paymentInfo0.getSecurityCode());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PaymentInfo paymentInfo0 = new PaymentInfo(1, 2377, "|t(?w|E.B", "L%P\"uOcS>V", 1);
      paymentInfo0.setExpDate(0);
      int int0 = paymentInfo0.getExpDate();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PaymentInfo paymentInfo0 = new PaymentInfo(1, 2377, "|t(?w|E.B", "L%P\"uOcS>V", 1);
      int int0 = paymentInfo0.getSecurityCode();
      assertEquals("L%P\"uOcS>V", paymentInfo0.getBillingName());
      assertEquals(1, int0);
      assertEquals(2377, paymentInfo0.getExpDate());
      assertEquals("|t(?w|E.B", paymentInfo0.getBillingAddress());
      assertEquals(1, paymentInfo0.getCardNum());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PaymentInfo paymentInfo0 = new PaymentInfo(1, 2377, "|t(?w|E.B", "L%P\"uOcS>V", 1);
      String string0 = paymentInfo0.getBillingName();
      assertEquals(2377, paymentInfo0.getExpDate());
      assertEquals("|t(?w|E.B", paymentInfo0.getBillingAddress());
      assertEquals("L%P\"uOcS>V", string0);
      assertEquals(1, paymentInfo0.getSecurityCode());
      assertEquals(1, paymentInfo0.getCardNum());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PaymentInfo paymentInfo0 = new PaymentInfo(1, 2377, "|t(?w|E.B", "L%P\"uOcS>V", 1);
      String string0 = paymentInfo0.getBillingAddress();
      assertEquals(1, paymentInfo0.getSecurityCode());
      assertEquals(1, paymentInfo0.getCardNum());
      assertEquals(2377, paymentInfo0.getExpDate());
      assertEquals("L%P\"uOcS>V", paymentInfo0.getBillingName());
      assertEquals("|t(?w|E.B", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      PaymentInfo paymentInfo0 = new PaymentInfo(1, 2377, "|t(?w|E.B", "L%P\"uOcS>V", 1);
      assertEquals(1, paymentInfo0.getSecurityCode());
      
      paymentInfo0.setSecurityCode((-1));
      assertEquals((-1), paymentInfo0.getSecurityCode());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PaymentInfo paymentInfo0 = new PaymentInfo(1, 2377, "|t(?w|E.B", "L%P\"uOcS>V", 1);
      int int0 = paymentInfo0.getExpDate();
      assertEquals("|t(?w|E.B", paymentInfo0.getBillingAddress());
      assertEquals("L%P\"uOcS>V", paymentInfo0.getBillingName());
      assertEquals(2377, int0);
      assertEquals(1, paymentInfo0.getSecurityCode());
      assertEquals(1, paymentInfo0.getCardNum());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      PaymentInfo paymentInfo0 = new PaymentInfo(1, 2377, "|t(?w|E.B", "L%P\"uOcS>V", 1);
      double double0 = paymentInfo0.getCardBallance();
      assertEquals(0.0, double0, 0.01);
      assertEquals(2377, paymentInfo0.getExpDate());
      assertEquals("|t(?w|E.B", paymentInfo0.getBillingAddress());
      assertEquals("L%P\"uOcS>V", paymentInfo0.getBillingName());
      assertEquals(1, paymentInfo0.getSecurityCode());
      assertEquals(1, paymentInfo0.getCardNum());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      PaymentInfo paymentInfo0 = new PaymentInfo(1, 2377, "|t(?w|E.B", "L%P\"uOcS>V", 1);
      MockDate mockDate0 = new MockDate(0, (-727), (-1248), (-1), 1);
      paymentInfo0.parkingInfo(2377, mockDate0, "|t(?w|E.B", "", (-1248));
      assertEquals("L%P\"uOcS>V", paymentInfo0.getBillingName());
      assertEquals(1, paymentInfo0.getSecurityCode());
      assertEquals(1, paymentInfo0.getCardNum());
      assertEquals(2377, paymentInfo0.getExpDate());
      assertEquals("|t(?w|E.B", paymentInfo0.getBillingAddress());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      PaymentInfo paymentInfo0 = new PaymentInfo(1, 2377, "|t(?w|E.B", "L%P\"uOcS>V", 1);
      paymentInfo0.setCardNum((-1248));
      int int0 = paymentInfo0.getCardNum();
      assertEquals((-1248), int0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      PaymentInfo paymentInfo0 = new PaymentInfo(1, 2377, "|t(?w|E.B", "L%P\"uOcS>V", 1);
      int int0 = paymentInfo0.getCardNum();
      assertEquals(1, paymentInfo0.getSecurityCode());
      assertEquals("L%P\"uOcS>V", paymentInfo0.getBillingName());
      assertEquals(1, int0);
      assertEquals("|t(?w|E.B", paymentInfo0.getBillingAddress());
      assertEquals(2377, paymentInfo0.getExpDate());
  }
}
