/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 29 23:14:18 GMT 2023
 */

package manager;

import org.junit.Test;
import static org.junit.Assert.*;
import manager.Manager;
import manager.SuperManager;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SuperManager_ESTest extends SuperManager_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SuperManager.getInstance();
      SuperManager superManager0 = SuperManager.getInstance();
      assertEquals("admin", superManager0.getUsername());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SuperManager superManager0 = SuperManager.getInstance();
      assertNotNull(superManager0);
      
      Manager manager0 = superManager0.autoGenerator();
      assertEquals("manager_1392409281320000", manager0.getUsername());
      assertEquals("password_1392409281320000", manager0.getPassword());
  }
}
