/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 29 23:30:51 GMT 2023
 */

package users;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import users.Visitor;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Visitor_ESTest extends Visitor_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Visitor visitor0 = new Visitor((String) null, (String) null);
      int int0 = visitor0.getParkingRate();
      assertEquals(15, int0);
  }
}
