/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 29 23:34:13 GMT 2023
 */

package test_evosuite;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import users.FacultyMember;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class FacultyMember_ESTest extends FacultyMember_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FacultyMember facultyMember0 = new FacultyMember("", "");
      int int0 = facultyMember0.getParkingRate();
      assertEquals(8, int0);
  }
}
