/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 29 23:21:14 GMT 2023
 */

package test_evosuite;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import parkingState.Unoccupied;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Unoccupied_ESTest extends Unoccupied_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Unoccupied unoccupied0 = new Unoccupied();
      String string0 = unoccupied0.handleState();
      assertEquals("", string0);
  }
}
